export const logos = [
  {
    key: "Apple",
    fields: [
      "email",
      "order_number",
      "order_date",
      "delivery_date",
      "image_link",
      "item",
      "full_name",
      "last_2_phone_number",
      "street",
      "city",
      "zip",
      "country",
      "subtotal",
      "shipping",
      "tax",
      "total",
    ],
  },
  {
    key: "Balenciaga",
    fields: [
      "email",
      "image_link",
      "item",
      "color",
      "size",
      "subtotal",
      "shipping",
      "total",
      "full_name",
      "street",
      "city",
      "zip",
    ],
  },
  {
    key: "DIOR",
    fields: [
      "email",
      "order_number",
      "full_name",
      "street",
      "city",
      "zip",
      "country",
      "image_link",
      "order_date",
      "item",
      "size",
      "subtotal",
      "shipping",
      "taxes",
      "total",
    ],
  },
  {
    key: "END.",
    fields: [
      "email",
      "order_number",
      "image_link",
      "item",
      "color",
      "size",
      "subtotal",
      "discount",
      "shipping",
      "tax",
      "total",
      "full_name",
      "street",
      "city",
      "zip",
      "eta",
    ],
  },
  {
    key: "Farfetch",
    fields: [
      "email",
      "language",
      "order_number",
      "full_name",
      "street",
      "city",
      "zip",
      "country",
      "image_link",
      "estimated_delivery_from",
      "estimated_delivery_to",
      "shipped_from",
      "brand",
      "item",
      "subtotal",
      "shipping",
      "taxes",
      "credit",
      "promotions",
      "total",
    ],
  },
  {
    key: "Hermès",
    fields: [
      "email",
      "order_date",
      "order_number",
      "image_link",
      "item",
      "color",
      "size",
      "reference_number",
      "subtotal",
      "shipping",
      "total",
      "full_name",
      "street",
      "city",
      "zip",
    ],
  },
  {
    key: "GOAT",
    fields: [
      "email",
      "order_number",
      "image_link",
      "style_id",
      "item_name",
      "size",
      "brand",
      "shoe_condition",
      "box_condition",
      "subtotal",
      "shipping",
      "tax",
      "goat_credit",
      "total",
      "full_name",
      "street",
      "city",
      "zip",
      "country",
    ],
  },
  {
    key: "Grailed",
    fields: [
      "email",
      "image_link",
      "brand",
      "item",
      "size",
      "full_name",
      "street",
      "city",
      "zip",
      "country",
      "subtotal",
      "taxes",
      "total",
      "seller_location",
      "seller_profile_image_link",
    ],
  },
  {
    key: "Louis Vuitton",
    fields: [
      "email",
      "order_number",
      "image_link",
      "item",
      "style_id",
      "color",
      "subtotal",
      "shipping",
      "total",
      "full_name",
      "street",
      "city",
      "zip",
      "country",
    ],
  },
  {
    key: "Moncler",
    fields: [
      "email",
      "order_number",
      "order_date",
      "image_link",
      "item",
      "size",
      "color",
      "eta",
      "subtotal",
      "shipping",
      "total",
      "full_name",
      "street",
      "city",
      "zip",
      "country",
      "payment_method",
    ],
  },
  {
    key: "SNKRS",
    fields: [
      "email",
      "full_name",
      "street",
      "city",
      "zip",
      "order_number",
      "order_date",
      "image_link",
      "item_name",
      "style_id",
      "size",
      "subtotal",
      "shipping",
      "tax",
      "total",
    ],
  },
  {
    key: "SSENSE",
    fields: [
      "email",
      "order_number",
      "order_date",
      "payment_method",
      "full_name",
      "street",
      "city",
      "zip",
      "country",
      "image_link",
      "item",
      "style_id",
      "size",
      "subtotal",
      "shipping",
      "taxes",
      "total",
    ],
  },
  {
    key: "Stadium Goods",
    fields: [
      "email",
      "order_number",
      "image_link",
      "item",
      "style_id",
      "subtotal",
      "shipping",
      "discount",
      "taxes",
      "total",
      "full_name",
      "street",
      "city",
      "zip",
      "country",
    ],
  },
  {
    key: "StockX",
    fields: [
      "email",
      "delivery_date",
      "item_name",
      "item_link",
      "image_link",
      "style_id",
      "size",
      "size_in_brackets",
      "order_number",
      "purchase_price",
      "tax_options",
      "amount",
      "processing_fee",
      "shipping",
      "total",
    ],
  },
  {
    key: "Trapstar",
    fields: [
      "email",
      "order_number",
      "image_link",
      "item",
      "size",
      "color",
      "subtotal",
      "shipping",
      "taxes",
      "total",
      "full_name",
      "street",
      "city",
      "zip",
      "country",
      "last_4_credit_card",
    ],
  },
  {
    key: "Nike",
    fields: [
      "email",
      "full_name",
      "street",
      "city",
      "zip",
      "order_number",
      "order_date",
      "delivery_date",
      "image_link",
      "item_name",
      "size",
      "last_4_credit_card",
      "subtotal",
      "shipping",
      "total",
    ],
  },
];
